table tbl_Afericoes
	lineageTag: 32d80a41-15c6-5f31-8241-bab6a2d532c0

	column Arquivo
		dataType: string
		lineageTag: 3072805a-5871-567f-bf72-9d576de06c29
		summarizeBy: none
		sourceColumn: Arquivo

		annotation SummarizationSetBy = Automatic

	column Ensaio
		dataType: string
		lineageTag: 8eb6d087-3910-551d-939f-e9509997141a
		summarizeBy: none
		sourceColumn: Ensaio

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 4c0bd74e-b8ae-5949-ae62-8cc16959ef53
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b1120c52-9caf-5560-8da9-2bfa7d135c5c
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Equipamento
		dataType: string
		lineageTag: e7b35492-9974-5594-be12-18811b250e7b
		summarizeBy: none
		sourceColumn: Equipamento

		annotation SummarizationSetBy = Automatic

	column Parâmetro
		dataType: string
		lineageTag: c9844ee4-3000-58c6-9b87-76cd58db273f
		summarizeBy: none
		sourceColumn: Parâmetro

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 6e1f16c0-59b3-5e0d-bcad-4b2e62a6a46d
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		formatString: #,0.00
		lineageTag: 6e31a5ad-12a2-5db4-8182-78349b37a816
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column Referência
		dataType: double
		formatString: #,0.00
		lineageTag: b009a338-e06d-544c-b447-21e9bcea9f90
		summarizeBy: none
		sourceColumn: Referência

		annotation SummarizationSetBy = Automatic

	column Diferença
		dataType: double
		formatString: #,0.00
		lineageTag: dcd51eed-b144-55c3-b9c4-862db7d02d4d
		summarizeBy: none
		sourceColumn: Diferença

		annotation SummarizationSetBy = Automatic

	column 'Lim. Inferior'
		dataType: double
		formatString: #,0.00
		lineageTag: a6b4b305-4a1b-5f22-a02f-4c0a118f5b16
		summarizeBy: none
		sourceColumn: Lim. Inferior

		annotation SummarizationSetBy = Automatic

	column 'Lim. Superior'
		dataType: double
		formatString: #,0.00
		lineageTag: f69c6e97-b627-5196-9e20-ae3978a8e6dc
		summarizeBy: none
		sourceColumn: Lim. Superior

		annotation SummarizationSetBy = Automatic

	column Tolerância
		dataType: double
		formatString: #,0.00
		lineageTag: bbcca4cb-011c-53e3-86b8-9f1289a4144f
		summarizeBy: none
		sourceColumn: Tolerância

		annotation SummarizationSetBy = Automatic

	column Resultado
		dataType: string
		lineageTag: f80a2865-488a-5280-85ae-2f72b63228b5
		summarizeBy: none
		sourceColumn: Resultado

		annotation SummarizationSetBy = Automatic

	column Responsável
		dataType: string
		lineageTag: cf0816e6-7786-539b-bf07-615f34ff8c96
		summarizeBy: none
		sourceColumn: Responsável

		annotation SummarizationSetBy = Automatic

	column Letra
		dataType: string
		lineageTag: e5689189-2f25-54a9-962a-81461fea22bb
		summarizeBy: none
		sourceColumn: Letra

		annotation SummarizationSetBy = Automatic

	column Observação
		dataType: string
		lineageTag: a32b32b4-b015-58ee-8201-7d9bd7554888
		summarizeBy: none
		sourceColumn: Observação

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: 05b18f49-b80a-5214-8106-e57ea7fb075f
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		isHidden
		lineageTag: 9961b20e-48d9-5de7-9f18-7c8004907ef7
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column Conforme
		dataType: int64
		formatString: 0
		lineageTag: 69bbcd22-041b-5474-8fc0-c01354f87588
		summarizeBy: sum
		sourceColumn: Conforme

		annotation SummarizationSetBy = Automatic

	column TagKey
		dataType: string
		lineageTag: 9f8d7162-5350-53e5-aee0-68c72b1877d7
		summarizeBy: none
		sourceColumn: TagKey

		annotation SummarizationSetBy = Automatic

	column 'Grupo Operacional'
		dataType: string
		lineageTag: 962637ca-e730-570c-a493-42b5fbbe237e
		summarizeBy: none
		sourceColumn: Grupo Operacional

		annotation SummarizationSetBy = Automatic

	column '% da Tolerância'
		dataType: double
		formatString: 0%
		lineageTag: 62d76576-0692-599c-9233-7f9df4f82cad
		summarizeBy: none
		sourceColumn: % da Tolerância

		annotation SummarizationSetBy = Automatic

	column Comparativo
		dataType: string
		lineageTag: 6381ea4f-bf71-5607-af3a-51759fc1f3f4
		summarizeBy: none
		sourceColumn: Comparativo

		annotation SummarizationSetBy = Automatic

	column 'Semana Início'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 646df690-b170-5e6a-b004-bb473a3869d0
		summarizeBy: none
		sourceColumn: Semana Início

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition tbl_Afericoes = m
		mode: import
		source =
				let
				    // ════════════════════════════════════════════════════════════════════════
				    // ►► COLE AQUI o link da PASTA do SharePoint onde ficam os arquivos mensais
				    //    "CALIBRAÇÃO MM - MÊS.xlsm" (o endereço do navegador com a pasta aberta,
				    //    ou o link "Copiar link" da pasta). Enquanto estiver com o texto abaixo,
				    //    as páginas de Aferições ficam vazias e o resto do painel funciona.
				    // ════════════════════════════════════════════════════════════════════════
				    PastaLink = "COLE_AQUI_O_LINK_DA_PASTA",
				
				    Colunas = { "Ensaio", "Tipo", "Data", "Equipamento", "Parâmetro", "Unidade", "Valor",
				                "Referência", "Diferença", "Lim. Inferior", "Lim. Superior", "Tolerância",
				                "Resultado", "Responsável", "Letra", "Observação", "Origem" },
				    Numericas = { "Data", "Valor", "Referência", "Diferença", "Lim. Inferior", "Lim. Superior", "Tolerância" },
				
				    Configurado = Text.StartsWith( Text.Lower( Text.Trim( PastaLink ) ), "https://" ),
				
				    // link do navegador ou de compartilhamento: tira "?..." e o prefixo "/:f:/r"
				    SemQuery = let t = Text.Trim( PastaLink ) in if Text.Contains( t, "?" ) then Text.BeforeDelimiter( t, "?" ) else t,
				    Limpo    = Text.Replace( Text.Replace( SemQuery, "/:f:/r/", "/" ), "/:f:/s/", "/" ),
				    Partes   = Text.Split( Limpo, "/" ),
				    // https: | "" | servidor | sites | <site>  ->  as 5 primeiras partes formam o site
				    Site     = Text.Combine( List.FirstN( Partes, 5 ), "/" ),
				    // compara sempre no formato codificado (%20, %C3%A7...), em minúsculas
				    Codificar = ( t as text ) as text =>
				        Text.Lower( Text.Combine( List.Transform( Text.Split( t, "/" ),
				            each if Text.Contains( _, ":" ) or Text.Contains( _, "%" ) then _ else Uri.EscapeDataString( _ ) ), "/" ) ),
				    Alvo     = Codificar( Limpo ),
				
				    Lido =
				        if not Configurado then null
				        else
				            let
				                Arquivos  = SharePoint.Files( Site, [ ApiVersion = 15 ] ),
				                DaPasta   = Table.SelectRows( Arquivos, each
				                                Text.StartsWith( Codificar( [Folder Path] ), Alvo )
				                                and Text.EndsWith( Text.Lower( [Name] ), ".xlsm" )
				                                and not Text.StartsWith( [Name], "~$" ) ),
				                // arquivo sem a tabela (mês antigo, cópia de trabalho) é ignorado, não quebra
				                ComDados  = Table.AddColumn( DaPasta, "Dados", each
				                                let
				                                    wb = try Excel.Workbook( [Content], null, true ) otherwise null,
				                                    t  = if wb = null then null
				                                         else Table.SelectRows( wb, each [Kind] = "Table" and [Name] = "tbl_Afericoes" )
				                                in
				                                    if t = null or Table.IsEmpty( t ) then null else t{0}[Data] ),
				                Validos   = Table.SelectRows( ComDados, each [Dados] <> null ),
				                Enxuto    = Table.SelectColumns( Validos, { "Name", "Dados" } ),
				                Renomeado = Table.RenameColumns( Enxuto, { { "Name", "Arquivo" } } ),
				                Expandido = Table.ExpandTableColumn( Renomeado, "Dados", Colunas )
				            in
				                Expandido,
				
				    Vazio = #table( List.Combine( { { "Arquivo" }, Colunas } ), {} ),
				    Base  = if Lido = null then Vazio else Lido,
				
				    // fórmula que devolve "" chega como texto vazio: vira null antes de tipar
				    SemVazio = Table.ReplaceValue( Base, "", null, Replacer.ReplaceValue, Numericas ),
				    Tipado   = Table.TransformColumnTypes( SemVazio, {
				                   { "Data", type date }, { "Valor", type number }, { "Referência", type number },
				                   { "Diferença", type number }, { "Lim. Inferior", type number },
				                   { "Lim. Superior", type number }, { "Tolerância", type number },
				                   { "Ensaio", type text }, { "Tipo", type text }, { "Equipamento", type text },
				                   { "Parâmetro", type text }, { "Unidade", type text }, { "Resultado", type text },
				                   { "Responsável", type text }, { "Letra", type text }, { "Observação", type text },
				                   { "Origem", type text }, { "Arquivo", type text } } ),
				    SemErro  = Table.ReplaceErrorValues( Tipado, List.Transform( Numericas, each { _, null } ) ),
				
				    // só o que foi de fato registrado: tem data e tem resultado
				    Registros = Table.SelectRows( SemErro, each [Data] <> null and [Resultado] <> null and [Resultado] <> "" ),
				
				    // o mesmo lançamento não entra duas vezes (arquivo copiado para o mês seguinte sem
				    // limpar): Origem é a célula da aba de preenchimento, única dentro do arquivo
				    Chave  = Table.AddColumn( Registros, "Chave", each
				                 [Origem] & "|" & [Parâmetro] & "|" & Date.ToText( [Data], "yyyy-MM-dd" ), type text ),
				    Unicos = Table.Distinct( Chave, { "Chave" } ),
				
				    Conforme = Table.AddColumn( Unicos, "Conforme",
				                   each if [Resultado] = "Não conforme" then 0 else if [Resultado] = "Conforme" then 1 else null,
				                   Int64.Type ),
				
				    // TAG normalizada: "66AN11 x Estufa" -> 66AN11 · "66TA05 (5 kg) ..." -> 66TA05 · "PN  497" -> PN497
				    TagKey = Table.AddColumn( Conforme, "TagKey", each
				                 let
				                     e  = if [Equipamento] = null then "" else [Equipamento],
				                     b1 = if Text.Contains( e, " x " ) then Text.BeforeDelimiter( e, " x " ) else e,
				                     b2 = if Text.Contains( b1, " (" ) then Text.BeforeDelimiter( b1, " (" ) else b1
				                 in
				                     Text.Upper( Text.Remove( b2, { " ", "-", Character.FromNumber( 160 ) } ) ), type text ),
				
				    // família de instrumento: liga a aferição à "saúde por grupo" da Visão Geral
				    Grupo = Table.AddColumn( TagKey, "Grupo Operacional", each
				                if      Text.StartsWith( [TagKey], "66TA" ) and [Ensaio] = "Tambor de Abrasão" then "Tambores de Abrasão"
				                else if Text.StartsWith( [TagKey], "66AG" ) then "Peneiradores Alpine"
				                else if Text.StartsWith( [TagKey], "66PS" ) then "Prensas de Compressão"
				                else if Text.StartsWith( [TagKey], "66AN" ) then "Analisadores de Umidade"
				                else null, type nullable text ),
				
				    PctTol = Table.AddColumn( Grupo, "% da Tolerância", each
				                 if [Tolerância] <> null and [Tolerância] > 0 and [Diferença] <> null
				                 then Number.Abs( [Diferença] ) / [Tolerância] else null, type nullable number ),
				
				    Comparativo = Table.AddColumn( PctTol, "Comparativo", each
				                      [Equipamento] & " · " & [Parâmetro], type text ),
				
				    Semana = Table.AddColumn( Comparativo, "Semana Início", each Date.StartOfWeek( [Data], Day.Monday ), type date )
				in
				    Semana

	annotation PBI_ResultType = Table
