table tbl_Medicoes_Operacionais
	lineageTag: 59e9f1a2-81a5-4a4a-917e-4f6dddf8f4df

	column ID_Inspecao
		dataType: string
		lineageTag: 8e06d68a-42a7-4423-a344-c3b09586dd1f
		summarizeBy: none
		sourceColumn: ID_Inspecao

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 21b4aa30-42a2-4959-936b-12e0afffb4c7
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

	column Equip_Tag
		dataType: string
		lineageTag: a17848ea-7812-49f7-9c4f-f5b57ba47473
		summarizeBy: none
		sourceColumn: Equip_Tag

		annotation SummarizationSetBy = Automatic

	column Equipamento
		dataType: string
		lineageTag: 7e518302-51d9-44b6-a470-823dcdb8ceb5
		summarizeBy: none
		sourceColumn: Equipamento

		annotation SummarizationSetBy = Automatic

	column Comprimento_Cortador
		dataType: double
		formatString: #,0.000
		lineageTag: 73cff8c0-49c4-40bd-a612-682d9ee51b25
		summarizeBy: sum
		sourceColumn: Comprimento_Cortador

		annotation SummarizationSetBy = Automatic

	column Distancia_Percurso
		dataType: double
		formatString: #,0.000
		lineageTag: 4b8152c5-7b21-4c03-9e87-4eafe8914753
		summarizeBy: sum
		sourceColumn: Distancia_Percurso

		annotation SummarizationSetBy = Automatic

	column Tempo_1
		dataType: double
		formatString: #,0.000
		lineageTag: ee293796-cf01-4e4c-8d40-8f20e174abc5
		summarizeBy: sum
		sourceColumn: Tempo_1

		annotation SummarizationSetBy = Automatic

	column Tempo_2
		dataType: double
		formatString: #,0.000
		lineageTag: 2fba3421-92ec-4c61-a5e5-41329960b1c0
		summarizeBy: sum
		sourceColumn: Tempo_2

		annotation SummarizationSetBy = Automatic

	column Tempo_3
		dataType: double
		formatString: #,0.000
		lineageTag: 331102c5-95de-468a-8084-f4e16c10495e
		summarizeBy: sum
		sourceColumn: Tempo_3

		annotation SummarizationSetBy = Automatic

	column Tempo_4
		dataType: double
		formatString: #,0.000
		lineageTag: 7601a7e2-668c-4042-8059-c5b9896ee5de
		summarizeBy: sum
		sourceColumn: Tempo_4

		annotation SummarizationSetBy = Automatic

	column Tempo_5
		dataType: double
		formatString: #,0.000
		lineageTag: 75868871-f87a-4b6f-bf52-cb428095b82e
		summarizeBy: sum
		sourceColumn: Tempo_5

		annotation SummarizationSetBy = Automatic

	column Tempo_Medio
		dataType: double
		formatString: #,0.000
		lineageTag: 8ed709c5-e977-406c-9462-a7e81504ec6a
		summarizeBy: sum
		sourceColumn: Tempo_Medio

		annotation SummarizationSetBy = Automatic

	column Velocidade_Calculada
		dataType: double
		formatString: #,0.000
		lineageTag: b5b0788f-9364-494a-9e84-36ca6b3e1b68
		summarizeBy: sum
		sourceColumn: Velocidade_Calculada

		annotation SummarizationSetBy = Automatic

	column Velocidade_Uniforme
		dataType: string
		lineageTag: 9c154b6f-733d-490f-97ac-c86769ddb4fc
		summarizeBy: none
		sourceColumn: Velocidade_Uniforme

		annotation SummarizationSetBy = Automatic

	column Resultado_Medicao
		dataType: string
		lineageTag: b07618ab-92ab-460d-b566-67f92d70bd95
		summarizeBy: none
		sourceColumn: Resultado_Medicao

		annotation SummarizationSetBy = Automatic

	column 'TagKey Inspecao'
		dataType: string
		isHidden
		lineageTag: 0c85e2b4-d05a-5be9-bd7a-468365e4b0b3
		summarizeBy: none
		sourceColumn: TagKey Inspecao

		annotation SummarizationSetBy = Automatic
	/// "Planilha" ou "Forms": de qual fonte a linha veio.
	column Origem
		dataType: string
		lineageTag: 9ef6f6a1-3f06-0a72-7855-f17e5dd695f5
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	partition tbl_Medicoes_Operacionais = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook( Web.Contents( "https://smineracao.sharepoint.com/sites/automacao/laboratorios/ZTESTE/Base_PowerBI_Gestao_Equipamentos.xlsx" ), null, true ),
				    // normaliza a chave: a coluna Tag mistura número, texto e espaços irregulares
				    fxTag = ( tag as any ) as nullable text =>
				        let
				            t = if tag = null then null else Text.Upper( Text.Trim( Text.From( tag ) ) ),
				            s = if t = null then null else Text.Remove( t, { " ", Character.FromNumber( 160 ) } )
				        in
				            if s = null or s = "" then null else s,
				    // interpreta os SEIS formatos que convivem nas colunas de data:
				    //   serial do Excel · data nativa · dd/mm/aaaa · dd/mm/aa · mm/aa · mm/aaaa
				    // fimDoMes=true usa o último dia quando o dia não foi informado (vencimentos)
				    fxData = ( valor as any, fimDoMes as logical ) as nullable date =>
				        let
				            ehData   = valor is date or valor is datetime or valor is datetimezone,
				            ehNumero = valor is number,
				            texto    = if valor = null then null else Text.Trim( Text.From( valor ) ),
				            vazio    = texto = null or texto = "",
				            porData   = if ehData then try Date.From( valor ) otherwise null else null,
				            porSerial = if ehNumero and valor > 1 and valor < 100000 then try Date.From( valor ) otherwise null else null,
				            partes    = if vazio then {} else Text.Split( texto, "/" ),
				            n         = List.Count( partes ),
				            nums      = List.Transform( partes, each try Number.FromText( Text.Trim( _ ) ) otherwise null ),
				            numerico  = n >= 2 and not List.Contains( nums, null ),
				            anoCheio  = ( a as number ) as number => if a < 100 then 2000 + a else a,
				            porCompleta =
				                if numerico and n = 3
				                then try #date( anoCheio( nums{2} ), nums{1}, nums{0} ) otherwise null
				                else null,
				            porMesAno =
				                if numerico and n = 2 then
				                    let p = try #date( anoCheio( nums{1} ), nums{0}, 1 ) otherwise null
				                    in  if p = null then null else if fimDoMes then Date.EndOfMonth( p ) else p
				                else null
				        in
				            if porData <> null then porData
				            else if porSerial <> null then porSerial
				            else if porCompleta <> null then porCompleta
				            else porMesAno,
				
				    Bruto = Fonte{[Item="tbl_Medicoes_Operacionais",Kind="Table"]}[Data],
				    SemVazias =
				        let
				            // U+00A0 (espaço não separável) chega do SharePoint em célula "vazia".
				            // Sem esta limpeza ele conta como conteúdo: a linha entra no modelo e o
				            // valor vira uma categoria em branco no gráfico.
				            Branco = { " ", "#(00A0)", "#(tab)", "#(cr)", "#(lf)" },
				            Limpo =
				                Table.TransformColumns(
				                    Bruto, {},
				                    ( v ) => if v is text
				                            then ( let t = Text.Trim( v, Branco ) in if t = "" then null else t )
				                            else v
				                )
				        in
				        Table.SelectRows(
				            Limpo,
				            each List.AnyTrue(
				                List.Transform(
				                    Table.ColumnNames( Limpo ),
				                    (c) => Record.Field( _, c ) <> null
				                )
				            )
				        ),
				
				    Tipos = Table.TransformColumnTypes(
				        SemVazias,
				        {
				            { "ID_Inspecao", type text }, { "Equip_Tag", type text },
				            { "Equipamento", type text }, { "Velocidade_Uniforme", type text },
				            { "Resultado_Medicao", type text }
				        },
				        "pt-BR"
				    ),
				
				    ComData  = Table.AddColumn( Tipos, "DataConv", each fxData( [Data], false ), type nullable date ),
				    TiraData = Table.RemoveColumns( ComData, { "Data" }, MissingField.Ignore ),
				    RenData  = Table.RenameColumns( TiraData, {{ "DataConv", "Data" }} ),
				
				    // decimais com vírgula ("0,471") chegavam como texto — o gráfico de
				    // velocidade contava ocorrências de texto em vez de medir velocidade
				    ParaNumero = List.Accumulate(
				        { "Comprimento_Cortador", "Distancia_Percurso", "Tempo_1", "Tempo_2",
				          "Tempo_3", "Tempo_4", "Tempo_5", "Tempo_Medio", "Velocidade_Calculada" },
				        RenData,
				        ( tab, col ) =>
				            if List.Contains( Table.ColumnNames( tab ), col )
				            then Table.TransformColumns( tab,
				                    {{ col,
				                      // Number.FromText usa a cultura do modelo (pt-BR), onde "." é separador de
				                      // MILHAR. Trocar a vírgula por ponto e não dizer a cultura fazia 0,471 virar
				                      // 471 e 0,47100000000000003 virar 4,71E+16. Daí o eixo em "6E+16".
				                      each try ( if _ is number
				                                 then Number.From( _ )
				                                 else Number.FromText( Text.Replace( Text.Trim( Text.From( _ ) ), ",", "." ), "en-US" ) )
				                           otherwise null,
				                      type nullable number }} )
				            else tab
				    ),
				
				    ComTagKey = Table.AddColumn( ParaNumero, "TagKey Inspecao", each fxTag( [Equip_Tag] ), type nullable text ),
				    DaPlanilha = Table.AddColumn( ComTagKey, "Origem", each "Planilha", type text ),
				
				    // ═══ Microsoft Forms ══════════════════════════════════════════════════════
				    // A planilha de respostas nomeia cada coluna com o TEXTO da pergunta e
				    // acrescenta sufixo numerico quando duas perguntas tem o mesmo enunciado
				    // (Tempo 1 / Tempo 11). Os nomes ainda chegam com espaco duplicado e espaco
				    // nao separavel. Por isso NADA aqui referencia nome exato de coluna: elas
				    // sao achadas por padrao sobre o nome normalizado. Assim, mexer no
				    // formulario nao quebra a consulta em silencio.
				    // URL inteira do arquivo, na mesma forma da planilha antiga (que ja autentica).
				    // Com pasta + RelativePath o Power BI testava a credencial contra a PASTA e recusava.
				    FonteForms = Excel.Workbook(
				        Web.Contents( "https://smineracao.sharepoint.com/sites/automacao/laboratorios/ZTESTE/Inspe%C3%A7%C3%A3o%20de%20Amostradores.xlsx" ),
				        null, true ),
				    // o arquivo de respostas tem uma tabela so: pega a primeira, qualquer que seja o nome
				    // (tbl_forms, tbl_inspecoes... renomear no SharePoint nao quebra mais a consulta)
				    BrutoForms = Table.SelectRows( FonteForms, each [Kind] = "Table" ){0}[Data],
				
				    BrancoF = { " ", "#(00A0)", "#(tab)", "#(cr)", "#(lf)" },
				    TextoF = ( v as any ) as nullable text =>
				        let t = if v = null then null else Text.Trim( Text.From( v ), BrancoF )
				        in  if t = null or t = "" then null else t,
				    NumF = ( v as any ) as nullable number =>
				        let t = TextoF( v )
				        in  if t = null then null
				            else try Number.FromText( Text.Replace( t, ",", "." ), "en-US" ) otherwise null,
				
				    AchataF = ( n as text ) as text =>
				        Text.Lower( Text.Remove( n, { " ", "#(00A0)", ".", "?", "(", ")", ",", ":", "-", "–", "/", "=", "·" } ) ),
				    ColsF = Table.ColumnNames( BrutoForms ),
				    ContemF = ( trecho as text ) as list => List.Select( ColsF, each Text.Contains( AchataF( _ ), trecho ) ),
				    PrimeiraF = ( trecho as text ) as nullable text =>
				        let l = ContemF( trecho ) in if List.Count( l ) = 0 then null else List.First( l ),
				    ExataF = ( nome as text ) as nullable text =>
				        let l = List.Select( ColsF, each AchataF( _ ) = nome )
				        in  if List.Count( l ) = 0 then null else List.Last( l ),
				
				    cId     = ExataF( "id" ),
				    cFim    = ExataF( "horadeconclusão" ),
				    cTurno  = ExataF( "turno" ),
				    // ha DUAS colunas "Nome": a identidade de quem enviou (do Forms) e a
				    // pergunta com o nome do inspetor. List.Last pega a pergunta, que vem depois.
				    cNome   = ExataF( "nome" ),
				    cCritic = ExataF( "criticidade" ),
				    cTag    = PrimeiraF( "tagdoequipamento" ),
				    colsDist = ContemF( "distânciadepercurso" ),   // uma por ramificação do formulário; só a escolhida vem preenchida
				    cFoto   = PrimeiraF( "fotodoequipamento" ),
				    cDescNC = PrimeiraF( "descrevaanãoconformidade" ),
				    colsTempo = List.Select( ColsF, each Text.StartsWith( AchataF( _ ), "tempo" ) ),
				    colsChk   = List.Select( ColsF, each Text.Contains( AchataF( _ ), "checklistdocortador" )
				                                   or Text.Contains( AchataF( _ ), "divisorrotativo" ) ),
				    colsObs   = ContemF( "observações" ),
				    colsReq   = ContemF( "encontroualguma" ),
				
				    CampoF = ( r as record, c as nullable text ) as any =>
				        if c = null then null else Record.FieldOrDefault( r, c, null ),
				    JuntaF = ( r as record, cols as list ) as nullable text =>
				        let v = List.Select( List.Transform( cols, ( c ) => TextoF( CampoF( r, c ) ) ), each _ <> null )
				        in  if List.Count( v ) = 0 then null else Text.Combine( v, " | " ),
				
				    LinhasF = Table.SelectRows( BrutoForms, each CampoF( _, cFim ) <> null ),
				    RegistrosF = List.Transform( Table.ToRecords( LinhasF ), ( r ) =>
				        let
				            fim    = CampoF( r, cFim ),
				            data   = if fim = null then null else Date.From( fim ),
				            bruto  = TextoF( CampoF( r, cTag ) ),
				            tag    = if bruto = null then null else TextoF( Text.BeforeDelimiter( bruto & "·", "·" ) ),
				            equip  = if bruto = null then null else TextoF( Text.AfterDelimiter( bruto, "·" ) ),
				            // so o bloco do tipo de equipamento escolhido vem preenchido;
				            // os outros ficam nulos, entao basta recolher os que tem valor
				            tempos = List.Select( List.Transform( colsTempo, ( c ) => NumF( CampoF( r, c ) ) ), each _ <> null ),
				            medio  = if List.Count( tempos ) = 0 then null else List.Average( tempos ),
				            checks = List.Select( List.Transform( colsChk, ( c ) => TextoF( CampoF( r, c ) ) ), each _ <> null ),
				            qtdNC  = List.Count( List.Select( checks, each Text.Contains( Text.Lower( _ ), "não conforme" ) ) ),
				            // a distancia e digitada em CENTIMETROS (ver LEIA-ME: o enunciado da
				            // pergunta usa metros com virgula e as respostas chegam sem a virgula)
				            distCm = List.First( List.Select( List.Transform( colsDist, ( c ) => NumF( CampoF( r, c ) ) ), each _ <> null ), null ),
				            veloc  = if medio = null or medio = 0 or distCm = null then null
				                     else Number.Round( distCm / 100 / medio, 3 ),
				            turnoF = let s = TextoF( CampoF( r, cTurno ) ) in
				                     if s = null then null
				                     else if Text.Upper( s ) = "ADM" then "Adm"
				                     else if Text.StartsWith( Text.Lower( s ), "letra " )
				                          then "Turno " & Text.Upper( Text.End( s, 1 ) )
				                     else if Text.StartsWith( Text.Lower( s ), "turno " )
				                          then "Turno " & Text.Upper( Text.End( s, 1 ) )
				                     else s,
				            idIns  = "FORM-" & ( if data = null then "" else Date.ToText( data, "yyyyMMdd" ) )
				                     & "-" & ( if tag = null then "SEMTAG" else tag )
				                     & "-" & Text.PadStart( Text.From( CampoF( r, cId ) ), 4, "0" )
				        in
				            [ ID_Inspecao = idIns, Carimbo = fim, Data = data, Tag = tag, Equipamento = equip,
				              Turno = turnoF, Responsavel = TextoF( CampoF( r, cNome ) ),
				              Tempos = tempos, TempoMedio = medio, DistanciaCm = distCm, Velocidade = veloc,
				              QtdNC = qtdNC, Criticidade = TextoF( CampoF( r, cCritic ) ),
				              Observacoes = JuntaF( r, colsObs & { cDescNC } ),
				              RequerAcao = JuntaF( r, colsReq ),
				              Foto = TextoF( CampoF( r, cFoto ) ),
				              Checks = checks ] ),
				    Pega = ( l as list, i as number ) as nullable number =>
				        if List.Count( l ) > i then l{i} else null,
				
				    // #table com lista de nomes e lista de linhas: a forma mais simples de
				    // montar tabela em M, sem declaracao de tipo embutida
				    DoForms =
				        Table.TransformColumnTypes(
				            #table(
				                { "ID_Inspecao", "Data", "Equip_Tag", "Equipamento", "Comprimento_Cortador", "Distancia_Percurso", "Tempo_1", "Tempo_2", "Tempo_3", "Tempo_4", "Tempo_5", "Tempo_Medio", "Velocidade_Calculada", "Velocidade_Uniforme", "Resultado_Medicao", "TagKey Inspecao", "Origem" },
				                List.Transform( List.Select( RegistrosF, each List.Count( _[Tempos] ) > 0 ), ( x ) =>
				                    { x[ID_Inspecao],
				                      x[Data],
				                      x[Tag],
				                      x[Equipamento],
				                      null,
				                      if x[DistanciaCm] = null then null else x[DistanciaCm] * 10,
				                      Pega( x[Tempos], 0 ),
				                      Pega( x[Tempos], 1 ),
				                      Pega( x[Tempos], 2 ),
				                      Pega( x[Tempos], 3 ),
				                      Pega( x[Tempos], 4 ),
				                      if x[TempoMedio] = null then null else Number.Round( x[TempoMedio], 3 ),
				                      x[Velocidade],
				                      null,
				                      if x[QtdNC] = 0 then "Conforme" else "Nao Conforme",
				                      fxTag( x[Tag] ),
				                      "Forms"
				                    } )
				            ),
				            { { "Data", type date }, { "Distancia_Percurso", type number }, { "Tempo_1", type number }, { "Tempo_2", type number }, { "Tempo_3", type number }, { "Tempo_4", type number }, { "Tempo_5", type number }, { "Tempo_Medio", type number }, { "Velocidade_Calculada", type number } }
				        ),
				
				    Final = Table.Combine( { DaPlanilha, DoForms } )
				in
				    Final

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table
